Repository chingu-voyages/v36-toucans-team-04, pull requests merged in 2022-02, with the labels that each got.

#56 Feature/visual tutorial gif 12
  assets/common/css/tutorial.css
  assets/common/js/tutorial.js
  assets/images/bonusWord.png
  assets/images/correctlyTyped.png
  assets/images/difficulty.png
  assets/images/endGameButton.png
  assets/images/info.png
  assets/images/landingPage.png
  assets/images/mainFrame.png
  assets/images/mistyped.png
  assets/images/sky.gif
  assets/images/typeBox.png
  tutorial.html
Labels: user_story

#62 Fix possibly mismatching type on difficultyLevel
  assets/common/js/models/GameController.js
Labels: bug

#58 refactor/Landing Page - #11: Update the menu items
  assets/common/css/index.css
  index.html
Labels: task

#57 refactor/Game Over Screen - #17: Update buttons
  assets/common/js/game.js
  game.html
Labels: task

#65 Test and design difficulty levels parameters
  assets/common/js/models/GameDifficulty.js
Labels: task

#71 Add level up alert that flashes and displays for 4 seconds
  assets/common/css/game.css
  assets/common/js/game.js
  assets/common/js/models/GameController.js
  game.html
Labels: user_story, feature

#70 Change font style of the game interface
  assets/common/js/models/Canvas.js
  game.html
Labels: enhancement

#72 Feature/add additional difficulty levels 61
  assets/common/css/tutorial.css
  assets/common/js/models/dummy/CanvasDummy.js
  assets/common/js/models/dummy/GameControllerDummy.js
  assets/common/js/tutorial.js
  tutorial.html
Labels: user_story

#74 Update the label on the game over screen
  assets/common/js/models/GameController.js
  game.html
Labels: wontfix

#78 Update bonus word color and frequency
  assets/common/js/models/Canvas.js
  assets/common/js/models/GameController.js
Labels: enhancement

#80 Fix the scrollbar issue on Tutorial
  assets/common/js/models/dummy/GameControllerDummy.js
  assets/common/js/tutorial.js
Labels: bug

#81 Fix/falling speed 76
  assets/common/js/models/GameController.js
Labels: bug

#84 Adjust the layout of the credits page for smaller screen
  assets/common/css/credits.css
  credits.html
Labels: enhancement, task

#82 Add back button and adjusted layout
  assets/common/css/tutorial.css
  tutorial.html
Labels: enhancement, task
