Repository chingu-voyages/v36-toucans-team-04, pull requests merged in 2022-01, with the labels that each got.

#30 Feature/bonus word 23: Implemented Bonus Word
  assets/common/js/models/Canvas.js
  assets/common/js/models/GameController.js
  assets/common/js/models/Player.js
  assets/common/js/models/Word.js
Labels: user_story

#34 Feature/game page 13 - Refactored to use requestAnimationFrame to redraw canvas
  assets/common/js/models/GameController.js
Labels: user_story

#36 Feature/words color 14
  .gitignore
  assets/common/js/models/GameController.js
Labels: user_story

#37 Fix the issue with animation stopping
  assets/common/js/models/GameController.js
Labels: bug

#39 Feature/landing page 11 - Add Background Image
  assets/common/css/index.css
  assets/images/background.jpg
  assets/lib/bootstrap-4.6.1/css/bootstrap.min.css.map
  assets/lib/bootstrap-4.6.1/js/bootstrap.bundle.min.js.map
Labels: user_story

#38 Feature/game page 13 - Minor change to the background color
  assets/common/js/models/Canvas.js
Labels: user_story

#40 Feature/words success 15
  assets/common/js/models/GameController.js
Labels: user_story

#41 Feature/game over screen 17
  assets/common/css/game.css
  assets/common/js/game.js
  assets/common/js/models/GameController.js
  assets/common/js/models/Player.js
  credits.html
  game.html
  index.html
Labels: user_story

#47 Feature/game over screen 17
  assets/common/js/models/GameController.js
  assets/common/js/models/Player.js
  game.html
Labels: user_story

#51 Fun Facts Page - Issue #20
  assets/common/css/trivia.css
  trivia.html
Labels: user_story

#50 Credit-Page-18: Created the credit page
  assets/common/css/credits.css
  credits.html
Labels: user_story

#52 Game Over Screen - Issue #17
  assets/common/js/models/GameController.js
Labels: task

#53 Bonus Word - Issue #23
  assets/common/js/models/GameController.js
Labels: user_story

#55 Link tutorial page's column to selected game difficulty on game page
  assets/common/js/game.js
  assets/common/js/models/GameController.js
  assets/common/js/tutorial.js
Labels: user_story
